### ISSUE TITLE
broken labels in README

### ISSUE THREAD

**Issue by starlightknown** [pranavbaburaj/polyglot#7]
**Describe the bug**
Some of the labels in the project's README are not visible, maybe the link is broken. 
![broken](https://user-images.githubusercontent.com/74637789/117831163-f0823800-b291-11eb-80d6-8f776e2d0544.png)

**Comment by pranavbaburaj** [comment]
> Oops sorry might be some fault at my side. Thank you for responding. I'll close this

Thank you 🙂
